routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


// ini_set('memory_limit','512MB');
Route::get('/cron', ['as' => 'admin.cron', 'uses' => 'HomeController@runCron']);

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

// Route::get('/dashboard', 'HomeController@index')->name('dashboard');
// Route::post('adminLogin', 'AdminController@login')->name('adminLogin');

  Route::group(['prefix' => 'admin', 'middleware' =>['auth:web'] ],function () {

Route::get('/', function () {
    return view('AdminPanel.Dashboard');
});

Route::resource('services', 'ServiceController');
Route::any('services-delete', 'ServiceController@destroy');
Route::resource('model-services', 'ModelServicesController');
Route::resource('offers', 'OfferController');
Route::any('offer-delete', 'OfferController@destroy');
Route::resource('testimonial', 'TestimonialController');

Route::get('/ajax_upload', 'UserController@index');

Route::post('/ajax_upload/action', 'UserController@action')->name('ajaxupload.action');


Route::get('myform/ajax/{id}',array('as'=>'myform.ajax','uses'=>'AdminController@myformAjax'));


Route::post('/slider', 'AdminController@AddImage');

Route::get('/slider-image','AdminController@showSlider');
Route::post('/slider-image-edit','AdminController@EditSlider');
Route::get('/slider-image/delete/{id}',function($id){

	$delete=DB::delete('delete  from slider where id=?',[$id]);
	return Redirect::back()->with('success','successfully delete');

});

Route::post('/brandname','AdminController@AddBrand');
Route::get('/showbrandDetails','AdminEditController@showbrandDetails');
Route::post('/brand_name-edit','AdminEditController@editbrandDetails');
Route::get('/brand_details/{id}',function($id){

	$delete=DB::delete('delete  from brand_details where id=?',[$id]);
	return Redirect::back()->with('success','successfully delete');
});

Route::view('/questionanswer','AdminPanel/questionanswer');
Route::post('/questionAnswer','AdminController@questionAnswer');
Route::get('/showF&Q','AdminController@showqa');

Route::post('/brandmodel','AdminController@brandModel');
Route::get('/showModel','AdminEditController@showModel');
Route::post('/edit-model-page','AdminEditController@editbrandModel');
Route::get('/brand_edit-model/{id}','AdminEditController@EditModelPage');
Route::get('/brand_model/{id}', function($id){
$delete=DB::delete('delete  from brand_model where id=?',[$id]);
	return Redirect::back()->with('success','successfully delete');

});

Route::get('/terms-condition', 'AdminController@getTerms');
Route::post('/termsCondition','AdminController@terms');
Route::get('/terms','AdminController@showterms');
Route::post('/edit-termsCondition','AdminEditController@editTerms');

Route::view('/benifitsterms','AdminPanel/benifitAbout');
Route::post('/benifitsterms','AdminController@benifitabout');
Route::get('/benifit-view', 'AdminController@benifitshow');
Route::get('/benifit/edit/{id}', 'AdminController@shwbenifitshow');

// Route::post('/AvailableStatus','AdminController@Available');

Route::post('/AvailableStatus','AdminController@AvailableStatus');
Route::get('/show/AvailableStatus','AdminController@showavailable');
Route::post('/state-available-edit','AdminEditController@editStateDetails');

Route::post('/brandcolor','AdminController@brandcolor');
Route::get('/brandcolor-page','AdminEditController@brandcolor');
Route::post('/brandcolor-edit','AdminEditController@editbrandcolor');
Route::post('/brandcolor-delete','AdminEditController@deletebrandcolor');

Route::post('/About', 'AdminController@About12');

Route::view('/admin','AdminPanel/Dashboard');

Route::get('/about','AdminController@about');
Route::get('/about-edit','AdminController@showAbout');
Route::post('/About-edit/{id}','AdminController@editAbout');

Route::get('/admin-home','AdminController@home');
Route::get('/contact','AdminController@contact');

Route::get('users-list', 'AdminController@getAllUsers');
Route::post('user-delete', 'AdminEditController@deleteUser');
Route::delete('userDeleteAll', 'AdminController@deleteAll');

Route::get('orders', 'AdminController@getAllOrders');
Route::post('order-delete','AdminEditController@deleteorder');

Route::get('invoice/{id}', 'AdminController@getInvoice');

Route::get('edit-user-detail/{id}', 'AdminController@editUser');

Route::post('change-status', 'AdminController@changeOrderStatus');

Route::get('price', 'AdminController@getPrice');

Route::post('users-list/{id}',function($id){

	$delete=DB::delete('delete  from users where id=?',[$id]);
	return Redirect::back()->with('success','successfully delete');
});
});

app/Testimonial.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;

class Testimonial extends Model
{
  protected $fillable = ['image_url','client_name','rating','review','status','city','slug'];

  public function getCreatedAtAttribute($value)
    {
        $date = Carbon::parse($value);
        return $date->format('d-M-Y');
    }

    public function getImageUrlAttribute($value)
    {
      return 'images/' . $value;
    }

}

app/Http/Controllers/TestimonialController.php
<?php

namespace App\Http\Controllers;

use App\Testimonial;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Log;

class TestimonialController extends Controller
{
  /**
   * Display a listing of the resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function index(Request $request)
  {
    $order_by_column = 'created_at';
    $order_by_value = 'desc';
    if($request->has('service_name') || $request->has('service_status') || $request->has('order_by_column') || $request->has('order_by_value'))
      {
        $query = (new Testimonial)->newQuery();
          if($request->has('service_name') && $request->input('service_name') != ''){
            $query->where('service_name', 'Like', '%' . $request->input('service_name') . '%');
          }

          if($request->has('service_status') && $request->input('service_status') != 'all' && $request->input('service_status') != ''){
            $query->where('status', $request->input('service_status') );
          }

          if($request->has('order_by_column') && $request->input('order_by_column') != 'all' && $request->input('order_by_column') != ''){
            $order_by_column = $request->input('order_by_column');
          }

          if($request->has('order_by_value') && $request->input('order_by_value') != 'all' && $request->input('order_by_value') != ''){
            $order_by_value = $request->input('order_by_value');
          }

          $testimonials = $query->orderBy($order_by_column, $order_by_value)->paginate(10);
      } else {
          $testimonials = Testimonial::orderBy('created_at', 'desc')->paginate(10);
      }
      return view('AdminPanel.testimonial.index', compact('testimonials'));
  }

  /**
   * Show the form for creating a new resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function create()
  {
      return view('AdminPanel.testimonial.create');
  }

  /**
   * Store a newly created resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @return \Illuminate\Http\Response
   */
  public function store(Request $request)
  {
    // Log::info($request);
    $validator = Validator::make($request->toArray(), [
      'client_name'=>'required',
      'image_url'=>'required|mimes:jpeg,png,jpg,gif,svg|max:2000',
      'rating'=>'required',
      'review'=>'required',
      'status'=>'required',
    ]);

    if((count($validator->messages()) > 0) || ($validator->fails()))
       {
         return redirect()->back()->withErrors($validator->errors())->withInput($request->toArray());
       }
       if ($request->file('image_url')) {
           // Get image file
           $image = $request->file('image_url');
           $service_image =$this->imageUpload($image);
       }

       Testimonial::create([
         'client_name' => $request->client_name,
         'review' => $request->review,
         'rating' => $request->rating,
         'status' => $request->status,
         'city' => '',
         'image_url' => $service_image ]);

       return redirect('testimonial')->with('success', 'Sucessfully update the data');

  }

    /**
     * Display the specified resource.
     *
     * @param  \App\Testimonial  $testimonial
     * @return \Illuminate\Http\Response
     */
    public function show(Testimonial $testimonial)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Testimonial  $testimonial
     * @return \Illuminate\Http\Response
     */
    public function edit(Testimonial $testimonial)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Testimonial  $testimonial
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Testimonial $testimonial)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Testimonial  $testimonial
     * @return \Illuminate\Http\Response
     */
    public function destroy(Testimonial $testimonial)
    {
        //
    }
    /**
     * save image
     *
     * @param image file
     * @return uploaded image name
     */
     public function imageUpload($image)
     {
       // Make a image name based on user name and current timestamp
       $name = time();
       // Define folder path
       $folder = '/images/';
       // Make a file path where image will be stored [ folder path + file name + file extension]
       $filePath = $name. '.' . $image->getClientOriginalExtension();
       Log::info($filePath);
       // Upload image
       $file = $image->storeAs($folder, $name.'.'.$image->getClientOriginalExtension(), 'public');
       // $this->uploadOne($image, $folder, 'public', $name);
       // Set user profile image path in database to filePath
       return $filePath;
     }
}

resources/views/AdminPanel/testimonial/create.blade.php
@extends('layouts.Dashboard')

@section('content')
<div class="container-fluid" style="border:5px solid black;"style="background: #fff">
  <div class="row" >
   	<div class="col-sm-6" >
   	<h3 style="text-align: center;"><u><b>Create Testimonial</b></u></h3>

   </div>
  </div>
  <form method="POST" action="{{ route('testimonial.store') }}" enctype="multipart/form-data">
      @csrf
      <input type="text" name="city" hidden value="Bhind M.P.">
      <div class="row mb-2">
        <div class="form-group col-md-6">
            <label for="client_name" class="col-form-label text-md-right">{{ __('Client Name') }}</label>

            <input id="client_name" type="text" class="form-control @error('client_name') is-invalid @enderror" name="client_name" value="{{ old('client_name') }}" required autocomplete="client_name" autofocus>

            @error('client_name')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror
        </div>

        <div class="form-group col-md-6">
            <label for="image_url" class="col-form-label text-md-right">{{ __('Image') }}</label>

            <input id="image_url" type="file" class="form-control @error('image_url') is-invalid @enderror" name="image_url" value="{{ old('image_url') }}" required autocomplete="image_url" autofocus>

            @error('image_url')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror
        </div>
      </div>

      <div class="row mb-2">
        <div class="form-group col-md-6">
            <label for="rating" class="col-form-label text-md-right">{{ __('Rating') }}</label>
            <input id="rating" type="number" class="form-control @error('rating') is-invalid @enderror" name="rating" value="{{ old('rating') }}" required autocomplete="rating" autofocus>
            @error('rating')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror
        </div>
        <div class="form-group col-md-6">
            <label for="status" class=" col-form-label text-md-right">{{ __('Status') }}</label>
            <select id="status" type="text" class="form-control @error('status') is-invalid @enderror" name="status" value="{{ old('status') }}" required autocomplete="status" >
              <option value="active" >Active</option>
              <option value="inctive">Inactive</option>
            </select>
            @error('status')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror
        </div>
      </div>

      <div class="row mb-2">
        <div class="form-group col-md-12">
            <label for="review" class="col-form-label text-md-right">{{ __('Review') }}</label>
            <!-- <input id="review" type="text" class="form-control @error('review') is-invalid @enderror" name="review" value="{{ old('review') }}" required autocomplete="review" autofocus> -->
            <textarea rows="4" cols="80" id="review" type="text" class="form-control @error('review') is-invalid @enderror" name="review" value="{{ old('review') }}" required autocomplete="review" autofocus>
              {{ old('review') }}
            </textarea>

            @error('review')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror
        </div>
      </div>

      <div class="form-group row mb-0">
          <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                  {{ __('Submit') }}
              </button>
          </div>
      </div>
  </form>
</div>
@endsection

resources/views/AdminPanel/testimonial/index.blade.php
@extends('layouts.Dashboard')

@section('content')
	<div class="container">
    <div class="row">
      <div class="col-md-5">
        <a href="{{url('testimonial/create')}}" class="btn btn-info">Create</a>
      </div>
      <div class="col-md-7">
        <h4>Testimonials</h4>
      </div>
    </div>

		<div class="row mb-rem-1 search-content-row" >
      <!-- <form>
        <div class="col-md-3">
          <input type="text" class="form-control mb-2" value="{{request('service_name')}}" autocomplete="off" placeholder="Enter Service Name" name="service_name" style="font-size: 14px;">
        </div>
				<div class="col-md-2">
          <select name="service_status" class="form-control" id="service_status" value="{{request('service_status')}}">
            <option value="all" @if(request('service_status') == 'all') selected @endif>All</option>
            <option value="active" @if(request('service_status') == 'active') selected @endif >Active</option>
            <option value="inactive" @if(request('service_status') == 'inactive') selected @endif >Inactive</option>
          </select>
        </div>
        <div class="col-md-2">
          <select name="order_by_column" class="form-control" id="order_by_column" value="{{request('order_by_column')}}">
            <option value="all" @if(request('order_by_column') == 'all') selected @endif >Default</option>
						<option value="created_at" @if(request('order_by_column') == 'created_at')@endif >Created At</option>
            <option value="service_name" @if(request('order_by_column') == 'service_name') selected @endif>Service Name</option>
          </select>
        </div>
				<div class="col-md-3">
          <select name="order_by_value" class="form-control" id="order_by_value" value="{{request('order_by_value')}}">
            <option value="all" @if(request('order_by_value') == 'all') selected @endif >Default</option>
						<option value="desc" @if(request('order_by_value') == 'desc') selected @endif >Descending Order</option>
            <option value="asc" @if(request('order_by_value') == 'asc') selected @endif >Ascending Order</option>
          </select>
        </div>
        <div class="col-md-2">
          <button class="btn btn-info mb-2">Search</button>
        </div>
      </form> -->
    </div>

    <div class="table-responsive text-capitalize">
      <!--Table-->
      <table class="table table-striped table-bordered" style="width: 88%; overflow: auto">

        <thead style="background: #0066ff; color: #fff">
          <tr>
            <th scope="col">S.no.</th>
            <th scope="col">Client Name</th>
            <th scope="col">Image</th>
            <th scope="col">Review</th>
            <th scope="col">Rating</th>
            <th scope="col">Status</th>
            <th scope="col">Created At Date</th>
            <!-- <th scope="col" class="text-center" colspan="2">Action</th> -->
            <!-- <th scope="col">Delete</th> -->
           </tr>
        </thead>
        @if($testimonials)
        @forelse($testimonials as $row)
        <tbody>
          <tr scope="col" style="background: #e6f2ff;">
            <td>{{ $loop->iteration }}</td>
            <td>{{$row->client_name}}</td>
            <td><img src="{{$row->image_url }}" class="img-responsive" width="50" height="50" alt="testimonial image "></td>
            <td> {{$row->status}} </td>
						<td>{{str_limit($row->review, 70)}}</td>
						<td>{{$row->rating}}</td>
            <td>{!!$row->created_at!!}</td>
            <!-- <td><a href="/admin/services/{{$row->id}}/edit" class="btn btn-info">edit</a></td></td>
						<td><a href="/admin/model-services?serviceId={{$row->id}}" class="btn btn-info">Manage Model</a></td></td> -->
            <!-- <td><a href="services/{{$row->id}}/edit" class="btn btn-danger">Delete</a></td> -->
          </tr>
        </tbody>
       @empty
       <tbody>
         <tr scope="col" style="background: #e6f2ff;">
           <td colspan="7" class="text-center">
              <p style="color: red;">No Data Found</p></td>
         </tr>
       </tbody>
        @endforelse
        @endif
      </table>
	   </div>
	</div>
{!! $testimonials->links() !!}

@endsection