routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


// ini_set('memory_limit','512MB');
Route::get('/cron', ['as' => 'admin.cron', 'uses' => 'HomeController@runCron']);

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

// Route::get('/dashboard', 'HomeController@index')->name('dashboard');
// Route::post('adminLogin', 'AdminController@login')->name('adminLogin');

  Route::group(['prefix' => 'admin', 'middleware' =>['auth:web'] ],function () {

Route::get('/', function () {
    return view('AdminPanel.Dashboard');
});

Route::resource('services', 'ServiceController');
Route::any('services-delete', 'ServiceController@destroy');
Route::resource('model-services', 'ModelServicesController');
Route::resource('offers', 'OfferController');
Route::any('offer-delete', 'OfferController@destroy');
Route::resource('testimonial', 'TestimonialController');

Route::get('/ajax_upload', 'UserController@index');

Route::post('/ajax_upload/action', 'UserController@action')->name('ajaxupload.action');


Route::get('myform/ajax/{id}',array('as'=>'myform.ajax','uses'=>'AdminController@myformAjax'));


Route::post('/slider', 'AdminController@AddImage');

Route::get('/slider-image','AdminController@showSlider');
Route::post('/slider-image-edit','AdminController@EditSlider');
Route::get('/slider-image/delete/{id}',function($id){

	$delete=DB::delete('delete  from slider where id=?',[$id]);
	return Redirect::back()->with('success','successfully delete');

});

Route::post('/brandname','AdminController@AddBrand');
Route::get('/showbrandDetails','AdminEditController@showbrandDetails');
Route::post('/brand_name-edit','AdminEditController@editbrandDetails');
Route::get('/brand_details/{id}',function($id){

	$delete=DB::delete('delete  from brand_details where id=?',[$id]);
	return Redirect::back()->with('success','successfully delete');
});

Route::view('/questionanswer','AdminPanel/questionanswer');
Route::post('/questionAnswer','AdminController@questionAnswer');
Route::get('/showF&Q','AdminController@showqa');

Route::post('/brandmodel','AdminController@brandModel');
Route::get('/showModel','AdminEditController@showModel');
Route::post('/edit-model-page','AdminEditController@editbrandModel');
Route::get('/brand_edit-model/{id}','AdminEditController@EditModelPage');
Route::get('/brand_model/{id}', function($id){
$delete=DB::delete('delete  from brand_model where id=?',[$id]);
	return Redirect::back()->with('success','successfully delete');

});

Route::get('/terms-condition', 'AdminController@getTerms');
Route::post('/termsCondition','AdminController@terms');
Route::get('/terms','AdminController@showterms');
Route::post('/edit-termsCondition','AdminEditController@editTerms');

Route::view('/benifitsterms','AdminPanel/benifitAbout');
Route::post('/benifitsterms','AdminController@benifitabout');
Route::get('/benifit-view', 'AdminController@benifitshow');
Route::get('/benifit/edit/{id}', 'AdminController@shwbenifitshow');

// Route::post('/AvailableStatus','AdminController@Available');

Route::post('/AvailableStatus','AdminController@AvailableStatus');
Route::get('/show/AvailableStatus','AdminController@showavailable');
Route::post('/state-available-edit','AdminEditController@editStateDetails');

Route::post('/brandcolor','AdminController@brandcolor');
Route::get('/brandcolor-page','AdminEditController@brandcolor');
Route::post('/brandcolor-edit','AdminEditController@editbrandcolor');
Route::post('/brandcolor-delete','AdminEditController@deletebrandcolor');

Route::post('/About', 'AdminController@About12');

Route::view('/admin','AdminPanel/Dashboard');

Route::get('/about','AdminController@about');
Route::get('/about-edit','AdminController@showAbout');
Route::post('/About-edit/{id}','AdminController@editAbout');

Route::get('/admin-home','AdminController@home');
Route::get('/contact','AdminController@contact');

Route::get('users-list', 'AdminController@getAllUsers');
Route::post('user-delete', 'AdminEditController@deleteUser');
Route::delete('userDeleteAll', 'AdminController@deleteAll');

Route::get('orders', 'AdminController@getAllOrders');
Route::post('order-delete','AdminEditController@deleteorder');

Route::get('invoice/{id}', 'AdminController@getInvoice');

Route::get('edit-user-detail/{id}', 'AdminController@editUser');

Route::post('change-status', 'AdminController@changeOrderStatus');

Route::get('price', 'AdminController@getPrice');

Route::post('users-list/{id}',function($id){

	$delete=DB::delete('delete  from users where id=?',[$id]);
	return Redirect::back()->with('success','successfully delete');
});
});

app/ModelServices.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ModelServices extends Model
{
    //
    protected $fillable = ['model_id', 'service_id', 'actual_price', 'our_price', 'status'];

}

app/Http/Controllers/ModelServicesController.php
<?php

namespace App\Http\Controllers;

use App\ModelServices;
use App\brandModel;
use App\Service;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use DB;
use Log;

class ModelServicesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
      $serviceId = $request->serviceId;
      $serviceName = Service::where('id', $serviceId)->first()->service_name;

      if($serviceId){

        $query = DB::table('model_services')
                            ->join('brand_model', 'brand_model.id', '=', 'model_services.model_id')
                            ->where('model_services.service_id', $serviceId)
                            ->select(
                              'model_services.id as model_services_id',
                              'model_services.actual_price as actual_price',
                              'model_services.our_price as our_price',
                              'model_services.status as status',
                              'brand_model.*');

        $order_by_column = 'created_at';
        $order_by_value = 'desc';
        if($request->has('service_name') || $request->has('service_status') || $request->has('order_by_column') || $request->has('order_by_value'))
          {
              if($request->has('service_name') && $request->input('service_name') != ''){
                $query->where('brand_model.brand_model_name', 'Like', '%' . $request->input('service_name') . '%');
              }

              if($request->has('service_status') && $request->input('service_status') != 'all' && $request->input('service_status') != ''){
                $query->where('model_services.status', $request->input('service_status') );
              }

              if($request->has('order_by_column') && $request->input('order_by_column') != 'all' && $request->input('order_by_column') != ''){
                $order_by_column = $request->input('order_by_column');
              }

              if($request->has('order_by_value') && $request->input('order_by_value') != 'all' && $request->input('order_by_value') != ''){
                $order_by_value = $request->input('order_by_value');
              }

              $modelServices = $query->orderBy($order_by_column, $order_by_value)->paginate(20);
          } else {
            $modelServices = $query->orderBy('created_at', 'desc')->paginate(20);
          }

      }else {
        return redirect('services');
      }
      Log::info($modelServices);

      return view('AdminPanel.modelservices.index', compact('modelServices', 'serviceId', 'serviceName'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
      $serviceId = $request->serviceId;
      // Log::info($serviceId);
      $modelData = brandModel::select('id', 'brand_model_name')->get();
      // Log::info($modelData);
      return view('AdminPanel.modelservices.create', compact('modelData', 'serviceId' ));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      // Log::info($request);
      $validator = Validator::make($request->toArray(), [
        'service_id'=>'required',
        // 'model_id'=>'required|unique:model_services',
        'model_id'=>'required',
        'actual_price'=>'required|numeric',
        'our_price'=>'required|numeric',
        'status'=>'required',
      ]);

      if((count($validator->messages()) > 0) || ($validator->fails()))
         {
           return redirect()->back()->withErrors($validator->errors())->withInput($request->toArray());
         }
         ModelServices::create([
           'service_id' => $request->service_id,
           'model_id' => $request->model_id,
           'actual_price' => $request->actual_price,
           'our_price' => $request->our_price,
           'status' => $request->status
         ]);

         return redirect('model-services?serviceId='.$request->service_id)->with('success', 'Sucessfully created the data');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\ModelServices  $modelServices
     * @return \Illuminate\Http\Response
     */
    public function show(ModelServices $modelServices)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\ModelServices  $modelServices
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request, $modelServiceId)
    {
      $serviceId = $request->serviceId;
      $modelServices = ModelServices::where('id', $modelServiceId)->first();
      // Log::info($modelServiceId);
      // Log::info($modelServices);
      $modelData = brandModel::select('id', 'brand_model_name')->get();
        return view('AdminPanel.modelservices.edit', compact('modelServices', 'serviceId', 'modelData'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\ModelServices  $modelServices
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $modelServiceId)
    {
      // Log::info($request);
      $validator = Validator::make($request->toArray(), [
        'service_id'=>'required',
        // 'model_id'=>'required|unique:model_services,model_id,'.$modelServices->id,
        'actual_price'=>'required|numeric',
        'our_price'=>'required|numeric',
        'status'=>'required',
      ]);

      if((count($validator->messages()) > 0) || ($validator->fails()))
         {
           return redirect()->back()->withErrors($validator->errors())->withInput($request->toArray());
         }
         {
           $modelServices = ModelServices::where('id', $modelServiceId)->first();
           ModelServices::find($modelServices->id)->update(['actual_price' => $request->actual_price, 'our_price' => $request->our_price, 'status' => $request->status]);
         }

      return redirect('model-services?serviceId='.$request->service_id)->with('success','Model Service  updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\ModelServices  $modelServices
     * @return \Illuminate\Http\Response
     */
    public function destroy(ModelServices $modelServices)
    {
        //
    }
}

resources/views/AdminPanel/modelservices/create.blade.php
@extends('layouts.Dashboard')

@section('content')
<div class="container-fluid" style="border:5px solid black;"style="background: #fff">
  <div class="row" >
   	<div class="col-sm-12" >
   	<h3 style="text-align: center;"><u><b>Create Service</b></u></h3>

   </div>
  </div>
  <form method="POST" action="{{route('model-services.store')}}" enctype="multipart/form-data">
      @csrf
      <input type="text" name="service_id" value="{{$serviceId}}" hidden>
      <div class="row mb-2">
        <div class="form-group col-md-6">
            <label for="model_id" class="col-form-label text-md-right">{{ __('Model Name') }} <span class="text-danger"> *</span></label>
            <select id="model_id" class="form-control @error('model_id') is-invalid @enderror" name="model_id" value="{{ old('model_id') }}" required >
              <option value="" class="d-none">Select Model</option>
              @if($modelData)
                @foreach($modelData as $value)
                  <option value="{{$value->id}}">{{$value->brand_model_name}}</option>
                @endforeach
              @endif
            </select>
            <!-- <input id="model_id" type="text" class="form-control @error('model_id') is-invalid @enderror" name="model_id" value="{{ old('model_id') }}" required autocomplete="model_id" autofocus> -->

            @error('model_id')
                <span class="invalid-feedback text-danger" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror
        </div>

          <div class="form-group col-md-6">
              <label for="status" class=" col-form-label text-md-right">{{ __('Status') }} <span class="text-danger"> *</span></label>
              <!-- <input id="status" type="text" class="form-control @error('status') is-invalid @enderror" name="status" value="{{ old('status') }}" required autocomplete="status"> -->
              <select id="status" type="text" class="form-control @error('status') is-invalid @enderror" name="status" value="{{ old('status') }}" required autocomplete="status" >
                <option value="active" >Active</option>
                <option value="inctive">Inactive</option>
              </select>
              @error('status')
                  <span class="invalid-feedback text-danger " role="alert">
                      <strong>{{ $message }}</strong>
                  </span>
              @enderror
          </div>
      </div>

      <div class="row mb-2">
        <div class="form-group col-md-6">
            <label for="actual_price" class="col-form-label text-md-right">{{ __('Actual Price') }} <span class="text-danger"> *</span></label>
            <input id="actual_price" type="number" class="form-control @error('actual_price') is-invalid @enderror" name="actual_price" value="{{ old('actual_price') }}" required autocomplete="actual_price" autofocus>
            @error('actual_price')
                <span class="invalid-feedback text-danger" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror
        </div>

          <div class="form-group col-md-6">
              <label for="our_price" class=" col-form-label text-md-right">{{ __('Spazeme Price') }} <span class="text-danger"> *</span></label>
              <input id="our_price" type="number" class="form-control @error('our_price') is-invalid @enderror" name="our_price"
              value="{{ old('our_price') }}" required autocomplete="our_price">
              @error('our_price')
                  <span class="invalid-feedback text-danger" role="alert">
                      <strong>{{ $message }}</strong>
                  </span>
              @enderror
          </div>
      </div>
      <div class="form-group row mb-0">
          <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                  {{ __('Submit') }}
              </button>
          </div>
      </div>
  </form>
</div>
@endsection

resources/views/AdminPanel/modelservices/edit.blade.php
@extends('layouts.Dashboard')

@section('content')
<div class="container-fluid" style="border:5px solid black;"style="background: #fff">
  <div class="row" >
   	<div class="col-sm-12" >
   	<h3 style="text-align: center;"><u><b>Edit Service Model</b></u></h3>

   </div>
  </div>
  <form method="POST" action="{{route('model-services.update', $modelServices->id)}}" enctype="multipart/form-data">
      @csrf
      @method('PUT')
      <input type="text" name="service_id" value="{{$serviceId}}" hidden>
      <div class="row mb-2">
        <div class="form-group col-md-6">
            <label for="model_id" class="col-form-label text-md-right">{{ __('Model Name') }} <span class="text-danger"> *</span></label>
            <!-- <input id="model_id" type="text" class="form-control @error('model_id') is-invalid @enderror" name="model_id" value="{{  $modelServices->model_id }}" required autocomplete="model_id" autofocus> -->
            <select id="model_id" class="form-control @error('model_id') is-invalid @enderror" name="model_id" value="{{ $modelServices->model_id }}" required>
              <option value="" class="d-none">Select Model</option>
              @if($modelData)
                @foreach($modelData as $value)
                  <option value="{{$value->id}}" @if($value->id ==$modelServices->model_id) selected @endif >{{$value->brand_model_name}}</option>
                @endforeach
              @endif
            </select>

            @error('model_id')
                <span class="invalid-feedback text-danger" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror
        </div>

          <div class="form-group col-md-6">
              <label for="status" class=" col-form-label text-md-right">{{ __('Status') }} <span class="text-danger"> *</span></label>
              <!-- <input id="status" type="text" class="form-control @error('status') is-invalid @enderror" name="status" value="{{ old('status') }}" required autocomplete="status"> -->
              <select id="status" type="text" class="form-control @error('status') is-invalid @enderror" name="status" value="{{$modelServices->status }}" required autocomplete="status" >
                <option value="active" @if($modelServices->status == 'active') selected @endif >Active</option>
                <option value="inctive" @if($modelServices->status == 'inctive') selected @endif>Inactive</option>
              </select>
              @error('status')
                  <span class="invalid-feedback text-danger " role="alert">
                      <strong>{{ $message }}</strong>
                  </span>
              @enderror
          </div>
      </div>

      <div class="row mb-2">
        <div class="form-group col-md-6">
            <label for="actual_price" class="col-form-label text-md-right">{{ __('Actual Price') }} <span class="text-danger"> *</span></label>
            <input id="actual_price" type="number" class="form-control @error('actual_price') is-invalid @enderror" name="actual_price" value="{{ $modelServices->actual_price }}" required autocomplete="actual_price" autofocus>
            @error('actual_price')
                <span class="invalid-feedback text-danger" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror
        </div>

          <div class="form-group col-md-6">
              <label for="our_price" class=" col-form-label text-md-right">{{ __('Spazeme Price') }} <span class="text-danger"> *</span></label>
              <input id="our_price" type="number" class="form-control @error('our_price') is-invalid @enderror" name="our_price"
              value="{{$modelServices->our_price }}" required autocomplete="our_price">
              @error('our_price')
                  <span class="invalid-feedback text-danger" role="alert">
                      <strong>{{ $message }}</strong>
                  </span>
              @enderror
          </div>
      </div>
      <div class="form-group row mb-0">
          <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                  {{ __('Submit') }}
              </button>
          </div>
      </div>
  </form>
</div>
@endsection

resources/views/AdminPanel/modelservices/index.blade.php
@extends('layouts.Dashboard')

@section('content')
	<div class="container">
    <div class="row">
      <div class="col-md-5">
        <a href="model-services/create?serviceId={{$serviceId}}" class="btn btn-info">Create</a>
      </div>
      <div class="col-md-7">
        <h4>Models of {{$serviceName}} Service</h4>
      </div>
    </div>
    <div class="row mb-rem-1 search-content-row" >
      <form>
				<input type="text" name="serviceId" hidden value="{{$serviceId}}">
        <div class="col-md-3">
          <input type="text" class="form-control mb-2" value="{{request('service_name')}}" autocomplete="off" placeholder="Enter Model Name" name="service_name" style="font-size: 14px;">
        </div>
				<div class="col-md-2">
          <select name="service_status" class="form-control" id="service_status" value="{{request('service_status')}}">
            <option value="all" @if(request('service_status') == 'all') selected @endif>All</option>
            <option value="active" @if(request('service_status') == 'active') selected @endif >Active</option>
            <option value="inactive" @if(request('service_status') == 'inactive') selected @endif >Inactive</option>
          </select>
        </div>
        <div class="col-md-2">
          <select name="order_by_column" class="form-control" id="order_by_column" value="{{request('order_by_column')}}">
            <option value="all" @if(request('order_by_column') == 'all') selected @endif >Default</option>
						<option value="created_at" @if(request('order_by_column') == 'created_at')@endif >Created At</option>
            <option value="service_name" @if(request('order_by_column') == 'service_name') selected @endif>Service Name</option>
          </select>
        </div>
				<div class="col-md-3">
          <select name="order_by_value" class="form-control" id="order_by_value" value="{{request('order_by_value')}}">
            <option value="all" @if(request('order_by_value') == 'all') selected @endif >Default</option>
						<option value="desc" @if(request('order_by_value') == 'desc') selected @endif >Descending Order</option>
            <option value="asc" @if(request('order_by_value') == 'asc') selected @endif >Ascending Order</option>
          </select>
        </div>
        <div class="col-md-2">
          <button class="btn btn-info mb-2">Search</button>
        </div>
      </form>
    </div>

    <div class="table-responsive text-capitalize">
      <!--Table-->
      <table class="table table-striped table-bordered" style="width: 88%; overflow: auto">

        <thead style="background: #0066ff; color: #fff">
          <tr>
            <th scope="col">S.no.</th>
            <th scope="col">Model Name</th>
            <th scope="col">Actual Price</th>
            <th scope="col">Spazeme Price</th>
						<th scope="col">Status</th>
            <th scope="col">Edit</th>
            <!-- <th scope="col">Delete</th> -->
           </tr>
        </thead>
        @if($modelServices)
        @forelse($modelServices as $row)
        <tbody>
          <tr scope="col" style="background: #e6f2ff;">
            <td>{{ $loop->iteration }}</td>
            <td>{{$row->brand_model_name}}</td>
            <td> {{$row->actual_price}} </td>
            <td>{!!$row->our_price!!}</td>
						<td> {{$row->status}} </td>
            <td><a href="/admin/model-services/{{$row->model_services_id}}/edit?serviceId={{$serviceId}}" class="btn btn-info">edit</a></td></td>
            <!-- <td><a href="services/{{$row->id}}/edit" class="btn btn-danger">Delete</a></td> -->
          </tr>
        </tbody>
       @empty
       <tbody>
         <tr scope="col" style="background: #e6f2ff;">
           <td colspan="6" class="text-center">
              <p style="color: red;">No Data Found</p></td>
         </tr>
       </tbody>
        @endforelse
        @endif
      </table>
	   </div>
	</div>
{{--  --}}
{!! $modelServices->appends(request()->except('page'))->links() !!}

@endsection