routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


// ini_set('memory_limit','512MB');
Route::get('/cron', ['as' => 'admin.cron', 'uses' => 'HomeController@runCron']);

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

// Route::get('/dashboard', 'HomeController@index')->name('dashboard');
// Route::post('adminLogin', 'AdminController@login')->name('adminLogin');

  Route::group(['prefix' => 'admin', 'middleware' =>['auth:web'] ],function () {

Route::get('/', function () {
    return view('AdminPanel.Dashboard');
});

Route::resource('services', 'ServiceController');
Route::any('services-delete', 'ServiceController@destroy');
Route::resource('model-services', 'ModelServicesController');
Route::resource('offers', 'OfferController');
Route::any('offer-delete', 'OfferController@destroy');
Route::resource('testimonial', 'TestimonialController');

Route::get('/ajax_upload', 'UserController@index');

Route::post('/ajax_upload/action', 'UserController@action')->name('ajaxupload.action');


Route::get('myform/ajax/{id}',array('as'=>'myform.ajax','uses'=>'AdminController@myformAjax'));


Route::post('/slider', 'AdminController@AddImage');

Route::get('/slider-image','AdminController@showSlider');
Route::post('/slider-image-edit','AdminController@EditSlider');
Route::get('/slider-image/delete/{id}',function($id){

	$delete=DB::delete('delete  from slider where id=?',[$id]);
	return Redirect::back()->with('success','successfully delete');

});

Route::post('/brandname','AdminController@AddBrand');
Route::get('/showbrandDetails','AdminEditController@showbrandDetails');
Route::post('/brand_name-edit','AdminEditController@editbrandDetails');
Route::get('/brand_details/{id}',function($id){

	$delete=DB::delete('delete  from brand_details where id=?',[$id]);
	return Redirect::back()->with('success','successfully delete');
});

Route::view('/questionanswer','AdminPanel/questionanswer');
Route::post('/questionAnswer','AdminController@questionAnswer');
Route::get('/showF&Q','AdminController@showqa');

Route::post('/brandmodel','AdminController@brandModel');
Route::get('/showModel','AdminEditController@showModel');
Route::post('/edit-model-page','AdminEditController@editbrandModel');
Route::get('/brand_edit-model/{id}','AdminEditController@EditModelPage');
Route::get('/brand_model/{id}', function($id){
$delete=DB::delete('delete  from brand_model where id=?',[$id]);
	return Redirect::back()->with('success','successfully delete');

});

Route::get('/terms-condition', 'AdminController@getTerms');
Route::post('/termsCondition','AdminController@terms');
Route::get('/terms','AdminController@showterms');
Route::post('/edit-termsCondition','AdminEditController@editTerms');

Route::view('/benifitsterms','AdminPanel/benifitAbout');
Route::post('/benifitsterms','AdminController@benifitabout');
Route::get('/benifit-view', 'AdminController@benifitshow');
Route::get('/benifit/edit/{id}', 'AdminController@shwbenifitshow');

// Route::post('/AvailableStatus','AdminController@Available');

Route::post('/AvailableStatus','AdminController@AvailableStatus');
Route::get('/show/AvailableStatus','AdminController@showavailable');
Route::post('/state-available-edit','AdminEditController@editStateDetails');

Route::post('/brandcolor','AdminController@brandcolor');
Route::get('/brandcolor-page','AdminEditController@brandcolor');
Route::post('/brandcolor-edit','AdminEditController@editbrandcolor');
Route::post('/brandcolor-delete','AdminEditController@deletebrandcolor');

Route::post('/About', 'AdminController@About12');

Route::view('/admin','AdminPanel/Dashboard');

Route::get('/about','AdminController@about');
Route::get('/about-edit','AdminController@showAbout');
Route::post('/About-edit/{id}','AdminController@editAbout');

Route::get('/admin-home','AdminController@home');
Route::get('/contact','AdminController@contact');

Route::get('users-list', 'AdminController@getAllUsers');
Route::post('user-delete', 'AdminEditController@deleteUser');
Route::delete('userDeleteAll', 'AdminController@deleteAll');

Route::get('orders', 'AdminController@getAllOrders');
Route::post('order-delete','AdminEditController@deleteorder');

Route::get('invoice/{id}', 'AdminController@getInvoice');

Route::get('edit-user-detail/{id}', 'AdminController@editUser');

Route::post('change-status', 'AdminController@changeOrderStatus');

Route::get('price', 'AdminController@getPrice');

Route::post('users-list/{id}',function($id){

	$delete=DB::delete('delete  from users where id=?',[$id]);
	return Redirect::back()->with('success','successfully delete');
});
});

app/Offer.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Offer extends Model
{
    protected $fillable = ['offer_name', 'offer_code', 'offer_amount', 'offer_type', 'offer_on', 'offer_status'];
}

app/Http/Controllers/OfferController.php
<?php

namespace App\Http\Controllers;

use App\Offer;
use App\brandDetails;
use App\brandModel;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Log;


class OfferController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      $offers = Offer::all();
      return view('AdminPanel.offer.index', compact('offers'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
      $brands = brandDetails::orderBy('brand_name', 'asc')->get();
      $models = brandModel::orderBy('brand_model_name', 'asc')->get();
      return view('AdminPanel.offer.create', compact('brands', 'models'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      // Log::info($request);
      $validator = Validator::make($request->toArray(), [
        'offer_name'=>'required',
        'offer_code'=>'required',
        'offer_type'=>'required',
        'offer_amount'=>'required',
        'offer_status'=>'required',
      ]);

      if((count($validator->messages()) > 0) || ($validator->fails()))
       {
         return redirect()->back()->withErrors($validator->errors())->withInput($request->toArray());
       }
       $offer_on = 'all';
       if($request->offer_type == 'brand'){
          $offer_on =  $request->brand;
       }

       if($request->offer_type == 'model'){
          $offer_on =  $request->model;
       }
         Offer::create([
           'offer_name' => $request->offer_name,
           'offer_code' => $request->offer_code,
           'offer_type' => $request->offer_type,
           'offer_on' => $offer_on,
           'offer_amount' => $request->offer_amount,
           'offer_status' => $request->offer_status,
         ]);

         return redirect('offers')->with('success', 'Sucessfully update the data');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Offer  $offer
     * @return \Illuminate\Http\Response
     */
    public function show(Offer $offer)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Offer  $offer
     * @return \Illuminate\Http\Response
     */
    public function edit(Offer $offer)
    {
      $brands = brandDetails::orderBy('brand_name', 'asc')->get();
      $models = brandModel::orderBy('brand_model_name', 'asc')->get();
      return view('AdminPanel.offer.edit', compact('offer', 'brands', 'models'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Offer  $offer
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Offer $offer)
    {
      $validator = Validator::make($request->toArray(), [
        'offer_name'=>'required',
        'offer_code'=>'required',
        'offer_type'=>'required',
        'offer_amount'=>'required',
        'offer_status'=>'required',
      ]);

      if((count($validator->messages()) > 0) || ($validator->fails()))
       {
         return redirect()->back()->withErrors($validator->errors())->withInput($request->toArray());
       }
       $offer_on = 'all';
       if($request->offer_type == 'brand'){
          $offer_on =  $request->brand_id;
       }

       if($request->offer_type == 'model'){
          $offer_on =  $request->model_id;
       }
         Offer::find($offer->id)->update([
           'offer_name' => $request->offer_name,
           'offer_code' => $request->offer_code,
           'offer_type' => $request->offer_type,
           'offer_on' => $offer_on,
           'offer_amount' => $request->offer_amount,
           'offer_status' => $request->offer_status,
         ]);

         return redirect('offers')->with('success', 'Sucessfully update the data');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Offer  $offer
     * @return \Illuminate\Http\Response
     */
     public function destroy(Request $request)
     {
       $delete = false;
       if (request('id')) {
         $delete = Offer::where('id', '=', request('id'))->delete();
       }
   		if($delete==true){
   		 return redirect()->back()->with('success', 'Data Deleted Sucessfully');
   		}else{
   		 return redirect()->back()->with('danger','error please check');
   		}
     }
}

resources/views/AdminPanel/offer/create.blade.php
@extends('layouts.Dashboard')

@section('content')

<style media="screen">
  .d-none{
    display: none;
  }
</style>
<script src="http://demo.itsolutionstuff.com/plugin/jquery.js"></script>

<div class="container-fluid" style="border:5px solid black;"style="background: #fff">
  <div class="row" >
   	<div class="col-sm-12" >
   	<h3 style="text-align: center;"><u><b>Create Offers</b></u></h3>

   </div>
  </div>
  <form method="POST" action="{{route('offers.store')}}" enctype="multipart/form-data">
      @csrf
      <div class="row mb-2">
        <div class="form-group col-md-4">
            <label for="offer_name" class="col-form-label text-md-right">{{ __('Offer Name') }} <span class="text-danger"> *</span></label>
            <input id="offer_name" type="text" class="form-control @error('offer_name') is-invalid @enderror" name="offer_name" value="{{ old('offer_name') }}" required autocomplete="offer_name" autofocus>
            @error('offer_name')
                <span class="invalid-feedback text-danger" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror
        </div>

        <div class="form-group col-md-4">
            <label for="offer_code" class="col-form-label text-md-right">{{ __('Offer Code') }} <span class="text-danger"> *</span></label>
            <input id="offer_code" type="text" class="form-control @error('offer_code') is-invalid @enderror" name="offer_code" value="{{ old('offer_code') }}" required autocomplete="offer_code" autofocus>
            @error('offer_code')
                <span class="invalid-feedback text-danger" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror
        </div>

        <div class="form-group col-md-4">
            <label for="offer_amount" class="col-form-label text-md-right">{{ __('Offer Price') }} <span class="text-danger"> *</span></label>
            <input id="offer_amount" type="number" class="form-control @error('offer_amount') is-invalid @enderror" name="offer_amount" value="{{ old('offer_amount') }}" required autocomplete="offer_amount" autofocus>
            @error('offer_amount')
                <span class="invalid-feedback text-danger" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror
        </div>

      </div>

      <div class="row mb-2">
        <div class="form-group col-md-4">
            <label for="offer_type" class=" col-form-label text-md-right">{{ __('Offer Type') }} <span class="text-danger"> *</span></label>
            <select id="offer_type" type="text" class="form-control @error('offer_type') is-invalid @enderror" name="offer_type" value="{{ old('offer_type') }}" required autocomplete="offer_type" >
              <option value="" >Select Offer Type</option>
              <option value="all" selected>All</option>
              <option value="brand">Brand</option>
              <option value="model">Model</option>
            </select>
            @error('offer_type')
                <span class="invalid-feedback text-danger " role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror
        </div>

        <div id="brand_div" class="form-group col-md-4 d-none">
            <label for="brand_id" class="col-form-label text-md-right">{{ __('Brand Name') }} <span class="text-danger"> *</span></label>
            <select id="brand_id" class="form-control @error('brand_id') is-invalid @enderror" name="brand_id" value="{{ old('brand_id') }}" >
              <option value="" class="d-none">Select Model</option>
              @if($brands)
                @foreach($brands as $value)
                  <option value="{{$value->id}}">{{$value->brand_name}}</option>
                @endforeach
              @endif
            </select>
            @error('brand_id')
                <span class="invalid-feedback text-danger" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror
        </div>

        <div id="model_div" class="form-group col-md-4 d-none">
            <label for="model_id" class="col-form-label text-md-right">{{ __('Model Name') }} <span class="text-danger"> *</span></label>
            <select id="model_id" class="form-control @error('model_id') is-invalid @enderror" name="model_id" value="{{ old('model_id') }}">
              <option value="" class="d-none">Select Model</option>
              @if($models)
                @foreach($models as $value)
                  <option value="{{$value->id}}">{{$value->brand_model_name}}</option>
                @endforeach
              @endif
            </select>
            @error('model_id')
                <span class="invalid-feedback text-danger" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror
        </div>

        <div class="form-group col-md-4">
            <label for="offer_status" class=" col-form-label text-md-right">{{ __('Status') }} <span class="text-danger"> *</span></label>
            <select id="offer_status" type="text" class="form-control @error('offer_status') is-invalid @enderror" name="offer_status" value="{{ old('offer_status') }}" required autocomplete="offer_status" >
              <option value="" >Select Status</option>
              <option value="active" >Active</option>
              <option value="inctive">Inactive</option>
            </select>
            @error('offer_status')
                <span class="invalid-feedback text-danger " role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror
        </div>
      </div>
      <div class="form-group row mb-0">
          <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                  {{ __('Submit') }}
              </button>
          </div>
      </div>
  </form>
</div>
<script type="text/javascript">
  $('#offer_type').on('change', function(e){
    e.preventDefault();
    var value = $(this).val();
    switch (value) {
      case 'all':
      // var id = $('#model_div').attr('class');
        $('#model_div').removeClass();
        $('#model_div').addClass('form-group col-md-4 d-none');
        $('#brand_div').removeClass();
        $('#brand_div').addClass('form-group col-md-4 d-none');
        break;

      case 'brand':
      // var id = $('#model_div').attr('class');
        $('#model_div').removeClass();
        $('#model_div').addClass('form-group col-md-4 d-none');
        $('#brand_div').removeClass();
        $('#brand_div').addClass('form-group col-md-4');
        break;

      case 'model':
        $('#model_div').removeClass();
        $('#model_div').addClass('form-group col-md-4');
        $('#brand_div').removeClass();
        $('#brand_div').addClass('form-group col-md-4 d-none');
        break;

      default:

    }
  });
</script>
@endsection

resources/views/AdminPanel/offer/edit.blade.php
@extends('layouts.Dashboard')

@section('content')

<style media="screen">
  .d-none{
    display: none;
  }
</style>
<script src="http://demo.itsolutionstuff.com/plugin/jquery.js"></script>

<div class="container-fluid" style="border:5px solid black;"style="background: #fff">
  <div class="row" >
   	<div class="col-sm-12" >
   	<h3 style="text-align: center;"><u><b>Edit Offer</b></u></h3>

   </div>
  </div>
  <form method="POST" action="{{route('offers.update', $offer->id)}}">
      @csrf
      @method('PUT')
      <div class="row mb-2">
        <div class="form-group col-md-4">
            <label for="offer_name" class="col-form-label text-md-right">{{ __('Offer Name') }} <span class="text-danger"> *</span></label>
            <input id="offer_name" type="text" class="form-control @error('offer_name') is-invalid @enderror" name="offer_name" value="{{ $offer->offer_name }}" required autocomplete="offer_name" autofocus>
            @error('offer_name')
                <span class="invalid-feedback text-danger" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror
        </div>

        <div class="form-group col-md-4">
            <label for="offer_code" class="col-form-label text-md-right">{{ __('Offer Code') }} <span class="text-danger"> *</span></label>
            <input id="offer_code" type="text" class="form-control @error('offer_code') is-invalid @enderror" name="offer_code" value="{{ $offer->offer_code}}" required autocomplete="offer_code" autofocus>
            @error('offer_code')
                <span class="invalid-feedback text-danger" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror
        </div>

        <div class="form-group col-md-4">
            <label for="offer_amount" class="col-form-label text-md-right">{{ __('Offer Price') }} <span class="text-danger"> *</span></label>
            <input id="offer_amount" type="number" class="form-control @error('offer_amount') is-invalid @enderror" name="offer_amount" value="{{$offer->offer_amount}}" required autocomplete="offer_amount" autofocus>
            @error('offer_amount')
                <span class="invalid-feedback text-danger" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror
        </div>

      </div>

      <div class="row mb-2">
        <div class="form-group col-md-4">
            <label for="offer_type" class=" col-form-label text-md-right">{{ __('Offer Type') }} <span class="text-danger"> *</span></label>
            <select id="offer_type" type="text" class="form-control @error('offer_type') is-invalid @enderror" name="offer_type" value="{{$offer->offer_type}}" required autocomplete="offer_type" >
              <option value="" >Select Offer Type</option>
              <option value="all" selected="{{$offer->offer_type}}">All</option>
              <option value="brand" selected="{{$offer->offer_type}}">Brand</option>
              <option value="model" selected="{{$offer->offer_type}}">Model</option>
            </select>
            @error('offer_type')
                <span class="invalid-feedback text-danger " role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror
        </div>

        <div id="brand_div" class="form-group col-md-4 d-none">
            <label for="brand_id" class="col-form-label text-md-right">{{ __('Brand Name') }} <span class="text-danger"> *</span></label>
            <select id="brand_id" class="form-control @error('brand_id') is-invalid @enderror" name="brand_id" value="{{$offer->brand_id}}" >
              <option value="" class="d-none">Select Model</option>
              @if($brands)
                @foreach($brands as $value)
                  <option value="{{$value->id}}" selected="{{$offer->brand_id}}">{{$value->brand_name}}</option>
                @endforeach
              @endif
            </select>
            @error('brand_id')
                <span class="invalid-feedback text-danger" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror
        </div>

        <div id="model_div" class="form-group col-md-4 d-none">
            <label for="model_id" class="col-form-label text-md-right">{{ __('Model Name') }} <span class="text-danger"> *</span></label>
            <select id="model_id" class="form-control @error('model_id') is-invalid @enderror" name="model_id" value="{{$offer->model_id }}">
              <option value="" class="d-none">Select Model</option>
              @if($models)
                @foreach($models as $value)
                  <option value="{{$value->id}}" selected="{{$offer->model_id}}">{{$value->brand_model_name}}</option>
                @endforeach
              @endif
            </select>
            @error('model_id')
                <span class="invalid-feedback text-danger" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror
        </div>

        <div class="form-group col-md-4">
            <label for="offer_status" class=" col-form-label text-md-right">{{ __('Status') }} <span class="text-danger"> *</span></label>
            <select id="offer_status" type="text" class="form-control @error('offer_status') is-invalid @enderror" name="offer_status" value="{{$offer->offer_status }}" required autocomplete="offer_status" >
              <option value="" >Select Status</option>
              <option value="active" @if($offer->offer_status == 'active') selected @endif>Active</option>
              <option value="inctive" @if($offer->offer_status == 'inctive') selected @endif>Inactive</option>
            </select>
            @error('offer_status')
                <span class="invalid-feedback text-danger " role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror
        </div>
      </div>
      <div class="form-group row mb-0">
          <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                  {{ __('Submit') }} {{$offer->brand_id}}
              </button>
          </div>
      </div>
  </form>
</div>
<script type="text/javascript">
// A $( document ).ready() block.
$( document ).ready(function() {
  @if($offer->brand_id)
    $('#brand_div').removeClass('d-none');
    console.log('hi');
  @endif
  @if($offer->model_id)
    $('#model_div').removeClass('d-none');
  @endif
});
  $('#offer_type').on('change', function(e){
    e.preventDefault();
    var value = $(this).val();
    switch (value) {
      case 'all':
      // var id = $('#model_div').attr('class');
        $('#model_div').removeClass();
        $('#model_div').addClass('form-group col-md-4 d-none');
        $('#brand_div').removeClass();
        $('#brand_div').addClass('form-group col-md-4 d-none');
        break;

      case 'brand':
      // var id = $('#model_div').attr('class');
        $('#model_div').removeClass();
        $('#model_div').addClass('form-group col-md-4 d-none');
        $('#brand_div').removeClass();
        $('#brand_div').addClass('form-group col-md-4');
        break;

      case 'model':
        $('#model_div').removeClass();
        $('#model_div').addClass('form-group col-md-4');
        $('#brand_div').removeClass();
        $('#brand_div').addClass('form-group col-md-4 d-none');
        break;

      default:

    }
  });
</script>
@endsection

resources/views/AdminPanel/offer/index.blade.php
@extends('layouts.Dashboard')

@section('content')
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>

	<div class="container">
    <div class="row">
      <div class="col-md-5">
        <a href="offers/create" class="btn btn-info">Create</a>
      </div>
      <div class="col-md-7">
        <h4>Offer Details</h4>
      </div>
    </div>
    <div class="table-responsive text-capitalize">
      <!--Table-->
      <table class="table table-striped table-bordered" style="width: 88%; overflow: auto">

        <thead style="background: #0066ff; color: #fff">
          <tr>
            <th scope="col">S.no.</th>
            <th scope="col">Name</th>
            <th scope="col">Code</th>
            <th scope="col">Type</th>
            <th scope="col">Price</th>
            <th scope="col">Offer On</th>
						<th scope="col">Status</th>
            <th scope="col">Edit</th>
            <th scope="col">Delete</th>
           </tr>
        </thead>
        @if($offers)
        @forelse($offers as $row)
        <tbody>
          <tr scope="col" style="background: #e6f2ff;">
            <td>{{ $loop->iteration }}</td>
            <td>{{$row->offer_name}}</td>
            <td> {{$row->offer_code}} </td>
            <td>{!!$row->offer_type!!}</td>
						<td>{{$row->offer_amount}}</td>
						<td> {{$row->offer_on}} </td>
            <td> {{$row->offer_status}} </td>
            <td><a href="/admin/offers/{{$row->id}}/edit" class="btn btn-info">edit</a></td></td>
            <!-- <td><a href="services/{{$row->id}}/edit" class="btn btn-danger">Delete</a></td> -->
						<td>
							<button type="button" data-myid="{{$row->id}}" class="btn btn-danger" data-toggle="modal"
				          data-target="#deleteModal" data-whatever="@mdo">Delete</button>
						</td>
          </tr>
        </tbody>
       @empty
       <tbody>
         <tr scope="col" style="background: #e6f2ff;">
           <td colspan="8" class="text-center">
              <p style="color: red;">No Data Found</p></td>
         </tr>
       </tbody>
        @endforelse
        @endif
      </table>
	   </div>
	</div>
	<!-- START delete model -->
	<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
	  <div class="modal-dialog" role="document">
	    <div class="modal-content">
	      <div class="modal-header">
	        <h5 class="modal-title" id="deleteModalLabel">Delete</h5>
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
	          <span aria-hidden="true">&times;</span>
	        </button>
	      </div>
	      <div class="modal-body">
	        <form action="offer-delete" method="POST">
						@method('DELETE')
	          @csrf
	          <div class="form-group">
	            <input type="text" name="id" class="form-control hidden" id="id">
	          </div>
						<div class="form-group">
							<h3>Are you sure want to delete this</h3>
						</div>
	          <div class="modal-footer">
			        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
			        <button type="submit"  class="btn btn-primary">Delete</button>
			      </div>
	        </form>
	      </div>
	    </div>
	  </div>
	</div>
	<!-- END delete model -->

	<script type="text/javascript">
	// delete confirm model method on open model
	$('#deleteModal').on('show.bs.modal', function (event) {
		var button = $(event.relatedTarget) // Button that triggered the modal
		var id = button.data('myid')
		var modal = $(this)
		modal.find('.modal-body #id').val(id)
	})
	</script>

@endsection